### ISSUE TITLE
Обновить ссылку на Windows версию

### ISSUE THREAD

**Issue by krimtsev** [maxim-saplin/cpdt_results#6]
Привет! На сайте ссылка на версию https://github.com/maxim-saplin/CrossPlatformDiskTest/releases/download/2.2.3WPF/CPDT.zip бьётся как Not found.
Если качать через github, то попадаем на версию по свежее https://github.com/maxim-saplin/CrossPlatformDiskTest/releases/download/2.3.3WPF/CPDT.zip

Успехов!

**Comment by krimtsev** [comment]
![Screenshot_13](https://user-images.githubusercontent.com/12584409/87996558-4fa46f80-cafb-11ea-9dd8-5a81d7bfe41f.png)
И чтобы не флудить, не пойму, почему мой показатель больше других, но я не появился в ТОПе?

**Comment by krimtsev** [comment]
![Screenshot_14](https://user-images.githubusercontent.com/12584409/87996626-79f62d00-cafb-11ea-99f8-b2ee5e76eb34.png)
И часто ловлю ошибку сценария

**Comment by maxim-saplin** [comment]
Спасибо, ссылку поправил.

**Comment by maxim-saplin** [comment]
По поводу ошибки скриптов в CPDT - это наследие 90-х в лице втроенного компонента IE, который должен в приложении открывать сайт с результатами, с последними обновлениями Windows 10 таких ошибок стало заметно больше.. Никак руки не дойдут, буду переходить на Edge WebView.

Насчет топа не понял вопроса.

**Comment by krimtsev** [comment]
На счет ТОПа.
Не пойму, почему у меня больше скорость, чем из ТОПа, но я не попадаю в ТОП
![Screenshot_15](https://user-images.githubusercontent.com/12584409/88050721-0df9e000-cb60-11ea-876d-c2c5c9f1f49b.png)

**Comment by maxim-saplin** [comment]
Каким образом вы туда должны попасть? У вас в браузере судя по всему открыт сайт и на фоне этого сайта открыто окно CPDT - где связь?)

**Comment by krimtsev** [comment]
В топе идут места
1 место - 9,1
2 место - 9,1
3 место - 8,99

У меня на скришоте 10,2. Разве у меня не больше других?

**Comment by maxim-saplin** [comment]
Если вопрос в том, что после запуска CPDT на вашей машине список на сайте CPDT должен автоматом обновиться, то такой фичи нету и пока не планируется. Список результатов обновляется вручную мной
