### ISSUE TITLE
Add Results Nokia 5.3

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/cpdt_results#8]
Nokia 5.3
(TA-1234)
2020, Snapdragon 665, 4/64GB
(Android 10)

![share](https://user-images.githubusercontent.com/36500228/89884787-b1279d80-dbd2-11ea-8bbb-ffb0a0ad85da.png)

**Comment by maxim-saplin** [comment]
3 runs and screenshot with collapsed results is welcome

**Comment by KovalevArtem** [comment]
![Screenshot_20200820-002405](https://user-images.githubusercontent.com/36500228/90763032-a9f94180-e2ee-11ea-9374-435dd6adb154.png)

**Comment by maxim-saplin** [comment]
Спасибо!
