### ISSUE TITLE
Add Results Xiaomi Mi 10 Lite 5G

### ISSUE THREAD

**Issue by KovalevArtem** [maxim-saplin/cpdt_results#9]
Xiaomi Mi 10 Lite 5G
(M2002J9G)
2020, Snapdragon 765G, 6/128 GB
MIUI 12.0.1 (Android 10)
![image](https://user-images.githubusercontent.com/36500228/90632836-b9648600-e22d-11ea-87ad-c404a94a9843.png)

**Comment by maxim-saplin** [comment]
Could you please make 3 runs and give screenshot with collapsed results

**Comment by KovalevArtem** [comment]
![image](https://user-images.githubusercontent.com/36500228/90676888-4a0a8880-e265-11ea-8370-0d73a82f963e.png)

**Comment by KovalevArtem** [comment]
![image](https://user-images.githubusercontent.com/36500228/90678488-6c050a80-e267-11ea-9f7d-ed83391557ef.png)

**Comment by maxim-saplin** [comment]
Спасибо, добавил!

**Comment by KovalevArtem** [comment]
![image](https://user-images.githubusercontent.com/36500228/127507399-086f68ee-2d7a-4b7d-b820-7c56f5786103.png)
One of the results apparently needs to be deleted...

**Comment by maxim-saplin** [comment]
Done
